package at.bestsolution.dart.server.api.model;

public enum RequestErrorCode {
	CONTENT_MODIFIED
	,FORMAT_INVALID_FILE
	,FORMAT_WITH_ERRORS
	,GET_ERRORS_INVALID_FILE
	,INVALID_ANALYSIS_ROOT
	,INVALID_EXECUTION_CONTEXT
	,INVALID_OVERLAY_CHANGE
	,INVALID_PARAMETER
	,INVALID_REQUEST
	,NO_INDEX_GENERATED
	,REFACTORING_REQUEST_CANCELLED
	,SERVER_ALREADY_STARTED
	,SERVER_ERROR
	,SORT_MEMBERS_INVALID_FILE
	,SORT_MEMBERS_PARSE_ERRORS
	,UNANALYZED_PRIORITY_FILES
	,UNKNOWN_REQUEST
	,UNKNOWN_SOURCE
	,UNSUPPORTED_FEATURE
}
